apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:khQEjivf1CmWKSV81wARySLNKiasOw==,iv:e8JoDiv45BRG7klSSYPCVMdp7zSPl/1a01emDnH/jDM=,tag:vHtmxEt+M68O12W72YntWA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:okzyjS1sIObV4G7e406+WnO7+zTU4Eg6WAkYQBD7,iv:gBFsYADN8OyI8/8RfCKO8UjNbSAciQ0p7LK409bBvpc=,tag:PXoywA4XuLqKWz6wDltglw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14r2wvxfn2qxkwfwnn6k8z9en5rv3xanpvm9k7vwsh9dv0k2a2dtqyr8qtl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuUG5hRnJuN1pFdEZGNVVO
            R1lFYmgwdXQ2cERGTWJqN1RmRTZLb0kwQVNJCkxyTU1meDBrUll4Vzc1dG1SemdR
            bzRiMTdrakJ5dmh2YjIxZWswRnJtRkEKLS0tIHJTY0Q1U3pYRWVsNWN3M1BrQzhq
            MjJTWWpIbWMwRjZ3b1huUnNJRlBEY2MKifpE6FndQwWbGDBMt9nY9SYg3Ejgb8G8
            ukz33hVtSkHCfFPebTZWZQOTx1n1T40oiJbwE95kB0SDbPw1qN/pdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-01T09:39:16Z"
    mac: ENC[AES256_GCM,data:T4rycZPKFdor+3n5M+/ffelBXOeQWuyAa6c7nYA3CIMygqtZc3poGdTKWQja1q2BlFQDYxTk8pZOPmM3rbWkCynPgpQ7RfeFvBXTD+48hUBsF/9rLNbvPG/meNnsLxgKfOFs5QXd1MZw/GpgJ9BPxzqJeCVivxfqhEyDYiUk+B8=,iv:XsaQjNnWLOXxlJDU9L5SZ6pOef+GKyvL48CnIPtFyCw=,tag:sgNVnAq4Rku1cUO2SWsTjQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
